# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "nCY59dOdC4qhvwf+CsZ2grhloMdtoWHqWpoSMVkx0+BPGvEhvPmvTdFL+nhnPEGmiSm6uzsB1/dZF8JH0x8c43pZnCjYITSQ+DH0AlwShkM8mlD+q457Xz7oFk5F3JflLDjMqSPgZBMhqoI/Bxi61twKGTrD4mhBzGNaaBoA3NTE3BgWh10hjyU3LQ8OPW79OB9gKSGFzbOGrntHtBKWRTEnLqbtZfb/X7pO4c65epiHHavR3SMVCYgCV+Ym/pLXOUD9CUqUm2S6OdJxjAjQX1A5bNxEPOtdT9SKn/DiVueJIeMiiVz4yzhW154qog6NWuqijQNbMcUZXRtMOOD2f6sWD7FlM3I/e6OBUlrj6KetmnN8b0tSCp8562A/HL7Vbd8lgLFvZY/JJJ/3Eag5ZvV4rKlXO0mqpSVGfISsmuI1ZGDCommQ84lKz9tirko3/CMRWz57/Ag+WhqGoOuFRgCiVFP6yf/Y1gymkr7wdWygGmPIaTzaHLoLxnG1tbUGFf3dYHwEG+53x+H+hmftNeS0vZW4VzC/1qBx0Jvohw3uLdfMO0rkrEJ8tl4Zt4pjugTyAlBML/MA6ytAExIWH6zQu8RsCSJrw+3Zehw/zrt7lNTQDio/H4hxCSuSV29alpE18sDY188eSTROyPxpPoSaJejiT7Id43l4236Jdiw="


before install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
