travis:
  secure:
    BINSTAR_TOKEN: XY8WTyILZyTM+l8QWs2AK0/6bOK6O/rF5yqx/tQRZUS3gFU60aEd4L24vVMrTjBo+p2DZa+GW/+O6ge4PaOZe3AATPc8N7gArSIxS3umc8MATwOXX3RJ4PDeiE/zWDb60uTYJycOy2HGLhtcg+cw95cCGJOfXKG5JIjEmPFl8q1sWuR0If26SVkEzOdZRE253U14iZ0Bo8dbxCAQZgq/djY+4lbyPbklE0zeVzHBinNdorCG16e+50CKzlEm3ZMgOGBvC/FRNVfViMLIh8oVjmqfCq0eVwt90G4lXlbXzLJ4h/LaMHzI+k14x4xvjdGH/dCojkVwybolMIDB1TA9nCoYfThI6zb7Jb5YC7C496zAwCVaT4lEBJeB136YS7Iyl7ubnlKgactCfoe3N4YP443GBkYdtgIJ55p0yWwuebfpDcOXlgVsxjSUtQVnYAKYXvqAVaFBAZEoTjU9ymfYtFoZ+Ne2F5+mOTGDdcgl/JscW8MuiRxRqRY2oM7RPpZJz9DRQKMfj4KbjbzKIqpb8VOdiQIY2CRkmNaaFvkwVpn9B+zuc26D9nLeeko9o85V89iWSzHkgWI7aAn9ZXCOH7ckbCQ8ICnqdLZx1SONy1uK10OYZ2zALThMmuOh4bMAbrrqCYIGcgXSjy/KuzNXbjFPZMg4ry+vlDufcPj5otY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
